/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;

/**
 *
 * @author ASUS
 */
public class StudentRegForm1 extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegForm1
     */
    public StudentRegForm1() {
        initComponents();
    }
    public void Clearfield(){
        TFname.setText("");
        TFContact.setText("");
        TFAddress.setText("");
        TFNIC.setText("");
        dobTF.setText("");
        
       
        TFemail.setText("");
        
       
        RBtnMale.setSelected(false);
        RBtnFemale.setSelected(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        TFContact = new javax.swing.JTextField();
        TFAddress = new javax.swing.JTextField();
        TFNIC = new javax.swing.JTextField();
        RBtnMale = new javax.swing.JRadioButton();
        RBtnFemale = new javax.swing.JRadioButton();
        TFemail = new javax.swing.JTextField();
        BtnClear = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        dobTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setText("Full Name");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 188, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel43.setText("Contact No:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 228, -1, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel44.setText("Address:");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel45.setText("Date of Birth");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 133, -1));

        jLabel50.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel50.setText("NIC:");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel46.setText("Gender:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel49.setText("E-mail:");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        jLabel41.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 102));
        jLabel41.setText("Register New Student");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 119, 462, -1));
        jPanel1.add(TFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 188, 339, -1));

        TFContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContactActionPerformed(evt);
            }
        });
        jPanel1.add(TFContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 228, 339, -1));

        TFAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAddressActionPerformed(evt);
            }
        });
        jPanel1.add(TFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 339, -1));
        jPanel1.add(TFNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 339, -1));

        RBtnMale.setText("Male");
        RBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnMaleActionPerformed(evt);
            }
        });
        jPanel1.add(RBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        RBtnFemale.setText("Female");
        RBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(RBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        jPanel1.add(TFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 339, 25));

        BtnClear.setBackground(new java.awt.Color(255, 255, 51));
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 80, 30));

        SubmitBtn.setBackground(new java.awt.Color(255, 255, 51));
        SubmitBtn.setText("Submit");
        SubmitBtn.setPreferredSize(new java.awt.Dimension(60, 25));
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 80, 30));

        BtnBack.setBackground(new java.awt.Color(255, 255, 51));
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 80, 30));

        dobTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTFActionPerformed(evt);
            }
        });
        jPanel1.add(dobTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 339, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));
        jPanel4.setForeground(new java.awt.Color(0, 51, 153));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Education");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFContactActionPerformed

    private void TFAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAddressActionPerformed

    private void RBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnMaleActionPerformed

    private void RBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtnFemaleActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        Clearfield();
        //Clearfield1();

    }//GEN-LAST:event_BtnClearActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String gender = null;

        if(RBtnMale.isSelected()){
            gender = "Male";
        }
        else if(RBtnFemale.isSelected()){
            gender = "Female";
        }


        InsertController.RegStu(TFname.getText(),TFContact.getText(),TFAddress.getText(),dobTF.getText(),TFNIC.getText(), gender, TFemail.getText());

        /*DBSearch var = new DBSearch();
        var.nic =
        `/*TFNIC.getText();/*/
        // PaymentDetails next = new PaymentDetails();
        // next.setVisible(true);
        // PaymentDetails p = new PaymentDetails();
        //p.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        AdminHome stdnew = new AdminHome();
        stdnew.setVisible(true);
        super.dispose();

    }//GEN-LAST:event_BtnBackActionPerformed

    private void dobTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dobTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JRadioButton RBtnFemale;
    private javax.swing.JRadioButton RBtnMale;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField TFAddress;
    private javax.swing.JTextField TFContact;
    public javax.swing.JTextField TFNIC;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
